image: ruby:2.7.1

services:
   - mysql:5.7.19

variables:
   RAILS_ENV: "test"
   COVERAGE: "true"
   MYSQL_HOST: "mysql"
   MYSQL_PASSWORD: "sinclair"
   MYSQL_ROOT_PASSWORD: "sinclair"
   MYSQL_DATABASE: "iflan_test"
   MYSQL_USER: "test"

before_script:
   - cp config/database.yml.example config/database.yml
   - cp config/secrets.yml.example  config/secrets.yml
   - mkdir -p reports/
   - bundle install --jobs 4 --deployment

stages:
   - test
   - production_deploy

test:
   script:
      - bundle exec rails db:drop db:create db:migrate
      - bundle exec rake iflan:coverage
      - bundle exec rake iflan:codereview
   tags:
      - docker
   coverage: '/\(\d+.\d+\%\) covered/'
   artifacts:
      paths:
         - reports/

Production_deploy:
   stage: production_deploy
   before_script:
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
   script:
      - bundle install --jobs 4 --deployment
      - bundle exec cap production deploy
   tags:
      - docker
   only:
      - master
   cache:
      key: ${CI_COMMIT_REF_SLUG}
      untracked: true
      paths:
         - vendor/bundle/