version: '3.8'
services:
   iflan-ws:
      container_name: iflan_ws
      build: .
      stdin_open: ${DOCKERTTY}
      tty: ${DOCKERTTY}
      volumes:
         - ./:/usr/src/iflan-ws
         - ~/.ssh:/root/.ssh
         - ./public/system:/usr/src/iflan-ws/public/system
      ports:
        - 3000:3000
      depends_on:
         - db

   db:
      container_name: iflan_db
      image: mysql:5.7.22
      volumes:
         - ./db/iflan_db_dev:/var/lib/iflan_db
      environment:
         MYSQL_ROOT_PASSWORD: sinclair
